### ISSUE TITLE
Stop?

### ISSUE THREAD

**Issue by SteveRMann** [stevemarple/AsyncDelay#3]
Is there no way to stop the timers?  One-shot as requested a year ago.

**Comment by stevemarple** [comment]
The timers are inherently one-shot. It's up to the user to call `repeat()` or `restart()` after the timer expires. I've added an example demonstrating one-shot usage.

There is no need to stop the timer, just don't call `isExpired()` if you don't need it any more. There is an `expire()` function that can be used to force a timer to be expire().

If you are looking for a stop command as  a mechanism to pause a timer then there isn't a specific function for this. However `getDuration()` will indicate how long a timer has been running for and `getDelay()` will return the original delay so you can save all the information needed in order to reuse the timer with a new call to `start()` when you wish to resume.
